source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!

xcodeproj 'tally'

pod 'OpenCV', '~> 2.4.10'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        puts "#{target.name}"
    end
end